import { useEffect, useState } from "react";
import * as THREE from "three";
import { wallTextureUrl, type WallSurfaceId } from "@/lib/walls";

// The wall behind the sign: a seamless photo-real texture for each surface
// (public/textures/walls, generated by scripts/generate-wall-textures.py) with
// a matching height map for relief. One tile covers TILE_UNITS of wall, so a
// brick stays a brick whatever the size of the nápis.

/**
 * World units one tile covers: 14 brick courses of 70 mm = 980 mm
 * (components/three/scale.ts) — the letters, their depth and the wall are all
 * measured in the same millimetres.
 */
export const TILE_UNITS = 2;
/** Brick courses in one tile — see TILE_UNITS. */
export const BRICK_ROWS_PER_TILE = 14;

export type WallTextures = { map: THREE.Texture; bump: THREE.Texture };

function prepare(t: THREE.Texture, planeWidth: number, planeHeight: number, srgb: boolean) {
  if (srgb) t.colorSpace = THREE.SRGBColorSpace;
  t.wrapS = t.wrapT = THREE.RepeatWrapping;
  t.repeat.set(planeWidth / TILE_UNITS, planeHeight / TILE_UNITS);
  // The wall is seen at a slant and, for a big nápis, from far away — without
  // anisotropic filtering the pattern shimmers into moiré. 16 is the ceiling
  // every GPU clamps to on its own.
  t.anisotropy = 16;
  t.needsUpdate = true;
}

/** The surface's colour and height textures, once both have loaded. */
export function useWallTexture(surface: WallSurfaceId, planeWidth: number, planeHeight: number) {
  const [loaded, setLoaded] = useState<{ surface: WallSurfaceId; tex: WallTextures } | null>(null);

  useEffect(() => {
    let cancelled = false;
    const loader = new THREE.TextureLoader();
    let got: WallTextures | null = null;
    Promise.all([
      loader.loadAsync(wallTextureUrl(surface, "color")),
      loader.loadAsync(wallTextureUrl(surface, "height")),
    ]).then(
      ([map, bump]) => {
        if (cancelled) {
          map.dispose();
          bump.dispose();
          return;
        }
        prepare(map, planeWidth, planeHeight, true);
        prepare(bump, planeWidth, planeHeight, false);
        got = { map, bump };
        setLoaded({ surface, tex: got });
      },
      () => {
        // A texture that will not load leaves the plain tinted wall.
      },
    );
    return () => {
      cancelled = true;
      if (got) {
        got.map.dispose();
        got.bump.dispose();
      }
    };
  }, [surface, planeWidth, planeHeight]);

  // Keeps showing the previous surface until the new one is in, rather than
  // flashing a blank wall between the two.
  return loaded?.tex ?? null;
}

/**
 * The customer's own photo of the wall. Loaded from an object URL created in
 * the browser — the file never leaves the page, and nothing about it is stored
 * with the order.
 */
/** Average colour of an image, for painting whatever lies beyond its edges. */
function averageColor(image: CanvasImageSource): string {
  try {
    const canvas = document.createElement("canvas");
    canvas.width = canvas.height = 8;
    const ctx = canvas.getContext("2d", { willReadFrequently: true });
    if (!ctx) return "#ffffff";
    ctx.drawImage(image, 0, 0, 8, 8);
    const { data } = ctx.getImageData(0, 0, 8, 8);
    let r = 0, g = 0, b = 0;
    for (let i = 0; i < data.length; i += 4) {
      r += data[i];
      g += data[i + 1];
      b += data[i + 2];
    }
    const n = data.length / 4;
    const hex = (v: number) => Math.round(v / n).toString(16).padStart(2, "0");
    return `#${hex(r)}${hex(g)}${hex(b)}`;
  } catch {
    return "#ffffff"; // a tainted canvas is not worth failing the preview over
  }
}

export type PhotoBackdrop = {
  texture: THREE.Texture;
  /**
   * The photo's average colour. The wall behind the photo is painted with it,
   * so the sliver that appears past the photo's edge at the far end of the
   * orbit blends in instead of flashing as a pale strip.
   */
  tint: string;
};

export function usePhotoTexture(url: string | null) {
  // Kept as a (url, texture) pair rather than a bare texture: a stale photo
  // then cannot flash into the preview while the new one is still decoding,
  // and nothing has to be reset from inside the effect body to prevent it.
  const [loaded, setLoaded] = useState<{ url: string; backdrop: PhotoBackdrop } | null>(null);

  useEffect(() => {
    if (!url) return;
    let cancelled = false;
    let texture: THREE.Texture | null = null;

    new THREE.TextureLoader().loadAsync(url).then(
      (t) => {
        if (cancelled) {
          t.dispose();
          return;
        }
        t.colorSpace = THREE.SRGBColorSpace;
        texture = t;
        setLoaded({ url, backdrop: { texture: t, tint: averageColor(t.image as CanvasImageSource) } });
      },
      () => {
        // A file the browser cannot decode — the painted wall stays.
      },
    );

    return () => {
      cancelled = true;
      texture?.dispose();
    };
  }, [url]);

  return url && loaded?.url === url ? loaded.backdrop : null;
}
